//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_media.khoabeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.Track_Artist = new HashSet<Track_Artist>();
            this.Track_Artist1 = new HashSet<Track_Artist>();
            this.Track_Playlist = new HashSet<Track_Playlist>();
            this.Track_Playlist1 = new HashSet<Track_Playlist>();
        }
    
        public int TrackID { get; set; }
        public string TrackName { get; set; }
        public Nullable<int> TrackLength { get; set; }
        public string TrackGenre { get; set; }
        public Nullable<int> AlbumID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Album Album1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_Artist> Track_Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_Artist> Track_Artist1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_Playlist> Track_Playlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_Playlist> Track_Playlist1 { get; set; }
    }
}
